export const FETCHING_WEATHER = 'FETCHING_WEATHER';
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS';
export const GET_WEATHER_ERR = 'GET_WEATHER_ERR';

export const FETCHING_FORECAST = 'FETCHING_FORECAST';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const GET_FORECAST_ERR = 'GET_FORECAST_ERR';